// <auto-generated />
using Accident_Detection_Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Accident_Detection_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Accident_Detection_Backend.Models.Accident", b =>
                {
                    b.Property<int>("Accident_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Accident_Id"));

                    b.Property<decimal?>("CabinForce")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Car_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("ImpactForce")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Impact_Side")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Accident_Id");

                    b.HasIndex("Car_Id");

                    b.ToTable("Accident");
                });

            modelBuilder.Entity("Accident_Detection_Backend.Models.Car", b =>
                {
                    b.Property<int>("Car_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Car_Id"));

                    b.Property<int>("Category_Id")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Registration_No")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Car_Id");

                    b.HasIndex("Category_Id");

                    b.HasIndex("Registration_No")
                        .IsUnique();

                    b.HasIndex("Uid");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Accident_Detection_Backend.Models.Category", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Category_Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Category_Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Accident_Detection_Backend.Models.NodeConnection", b =>
                {
                    b.Property<int>("Connection_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Connection_Id"));

                    b.Property<int>("Category_Id")
                        .HasColumnType("int");

                    b.Property<int>("From_Node")
                        .HasColumnType("int");

                    b.Property<int>("To_Node")
                        .HasColumnType("int");

                    b.HasKey("Connection_Id");

                    b.HasIndex("From_Node", "Category_Id");

                    b.HasIndex("To_Node", "Category_Id");

                    b.ToTable("NodeConnections");
                });

            modelBuilder.Entity("Accident_Detection_Backend.Models.Nodes", b =>
                {
                    b.Property<int>("Node_Id")
                        .HasColumnType("int");

                    b.Property<int>("Category_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Force")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Force_Value");

                    b.Property<string>("Node_Position")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Node_Id", "Category_Id");

                    b.HasIndex("Category_Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Accident_Detection_Backend.Models.User", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Contact_No")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Uid");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Accident_Detection_Backend.Models.Accident", b =>
                {
                    b.HasOne("Accident_Detection_Backend.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("Car_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Accident_Detection_Backend.Models.Car", b =>
                {
                    b.HasOne("Accident_Detection_Backend.Models.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accident_Detection_Backend.Models.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Accident_Detection_Backend.Models.NodeConnection", b =>
                {
                    b.HasOne("Accident_Detection_Backend.Models.Nodes", "Node")
                        .WithMany()
                        .HasForeignKey("From_Node", "Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accident_Detection_Backend.Models.Nodes", "Node1")
                        .WithMany()
                        .HasForeignKey("To_Node", "Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Node1");
                });

            modelBuilder.Entity("Accident_Detection_Backend.Models.Nodes", b =>
                {
                    b.HasOne("Accident_Detection_Backend.Models.Category", "Category")
                        .WithMany("Nodes")
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Accident_Detection_Backend.Models.Category", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Accident_Detection_Backend.Models.User", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
